Task1
Anton-Kraev/formal-lang-course pull request #1
Opened 2023-09-12 19:03 UTC by Anton-Kraev

2023-09-13 19:13 UTC, Pogozhelskaya requested changes

2023-09-13 19:13 UTC, Pogozhelskaya commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
+ Windows
+ MacOS

2023-09-13 19:13 UTC, Pogozhelskaya commented on tests/test_graph_info.py
> +    graph_utils.save_two_cycles_graph_in_dot(10, 20, ("first", "second"), "temp.dot")
Сравнение должно быть в явном виде. Заведите файл, пожалуйста, файл expected.dot

2023-09-13 19:13 UTC, Pogozhelskaya commented on project/graph_utils.py
> +def get_graph_info(name: str) -> Tuple[int, int, Set[Any]]:
```suggestion
def get_graph_info(name: str) -> Tuple[int, int, Set[str]]:
```

2023-09-13 19:53 UTC, Pogozhelskaya commented on project/graph_utils.py
> +    dot_graph = nx.drawing.nx_pydot.to_pydot(graph)
https://github.com/networkx/networkx/issues/5723

2023-09-14 20:29 UTC, Anton-Kraev commented
Исправил

2023-09-15 12:44 UTC, Pogozhelskaya commented on tests/test_graph_utils.py
> +    assert filecmp.cmp(expected_path, actual_path)
Вы уверены, что данная функция работает так, как Вы ожидаете?

2023-09-15 13:09 UTC, Pogozhelskaya approved these changes

2023-09-15 13:19 UTC, merged